################## Filebeat Pulpo Connector DE Configuration ##################

# This file is the configuration file for the filebeat running inside this
# beanstalk docker instance

#==========================  Modules configuration ============================

filebeat.prospectors:

#------------------------------ Log prospector --------------------------------
- input_type: log

  paths:
    - /var/log/aws/*.log
    - /var/log/aws/containers/*.log
    - /var/log/aws/containers/pulpo-connector-de/*.log

  exclude_lines: ["^GC"]

  multiline.pattern: '^%{TIME}'

  multiline.negate: false

  multiline.match: after

#================================ General ======================================

tags: ["pulpo-connector-de-dev"]

fields:
  env: dev
  service: pulpo-connector-de

#================================ Outputs ======================================

#-------------------------- Elasticsearch output -------------------------------
output.elasticsearch:
  hosts: ["search-pulpo-elasticsearch-log-dev-uk3rplqex6ciog3xy2jojrpsoa.eu-west-1.es.amazonaws.com:80"]

#----------------------------- Console output ---------------------------------
output.console:
  enabled: true

#================================ Logging ======================================
logging.level: info

logging.to_files: true
