################## Filebeat Pulpo Connector DE Configuration ##################

# This file is the configuration file for the filebeat running inside this
# beanstalk docker instance

#==========================  Modules configuration ============================

filebeat.prospectors:

#------------------------------ Log prospector --------------------------------
- input_type: log

  paths:
    - /var/log/aws/*.log
    - /var/log/aws/containers/*.log

  multiline.pattern: '^%{TIME}'

  multiline.negate: false

  multiline.match: after

  fields:
    type: beanstalk

- input_type: log

  paths:
    - /var/log/aws/containers/pulpo-connector-de/*.log

  exclude_lines: ["^GC"]

  multiline.pattern: '^%{TIME}'

  multiline.negate: false

  multiline.match: after

  fields:
    type: pulpo

#================================ General ======================================

tags: '${PULPO_CONNECTOR_BEAT_TAGS}'

fields:
  env: '${PULPO_CONNECTOR_BEAT_ENV}'
  service: '${PULPO_CONNECTOR_BEAT_SERVICE}'

#================================ Outputs ======================================

#-------------------------- Elasticsearch output -------------------------------
output.elasticsearch:
  hosts: '${PULPO_CONNECTOR_BEAT_ES_HOSTS}'

#----------------------------- Console output ---------------------------------
output.console:
  enabled: true

#================================ Logging ======================================
logging.level: info

logging.to_files: true
