################# Metricbeat Pulpo Connector DE Configuration #################

# This file is the configuration file for the metricbeat running inside this
# beanstalk docker instance

#================================ Outputs ======================================

#-------------------------- Elasticsearch output -------------------------------
output.elasticsearch:
  hosts: ["search-pulpo-elasticsearch-log-dev-uk3rplqex6ciog3xy2jojrpsoa.eu-west-1.es.amazonaws.com:80"]

#================================ Logging ======================================
logging.level: debug

logging.to_files: true